name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '**.toml'
      - 'docker-compose.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU and Docker Buildx
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build-docker-images:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: omznc/livelaunch-dashboard:${{ github.sha }}, omznc/livelaunch-dashboard:latest
